# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

monte_carlo_barrier_option <- function(n_sim, S0, K, r, sigma, T, barrier, is_call, is_down_and_out) {
    .Call('_BarrierOptionPricing_monte_carlo_barrier_option', PACKAGE = 'BarrierOptionPricing', n_sim, S0, K, r, sigma, T, barrier, is_call, is_down_and_out)
}

